# docker-compose.prod.yml
services:

  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: redis:7
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod     # ← build de producción
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SCHEDULE: "@daily"
      BACKUP_KEEP_DAYS: 7
      BACKUP_KEEP_WEEKS: 4
      BACKUP_KEEP_MONTHS: 6
    volumes:
      - ./backups:/backups

volumes:
  postgres_data: