services:

  db:
    image: postgres:15.6
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - ./backend/.env
    volumes:
      - ./backups:/backups
    environment:
      BACKUP_DIR: /backups

  redis:
    image: redis:7
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: