export const WSEvent = {
  ORDER_UPDATED: "ORDER_UPDATED",
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_ITEM_ADDED: "ORDER_ITEM_ADDED",
  ORDER_ITEM_REMOVED: "ORDER_ITEM_REMOVED",

  PAYMENT_ADDED: "PAYMENT_ADDED",

  CASH_REGISTER_UPDATED: "CASH_REGISTER_UPDATED",
  CASH_MOVEMENT_ADDED: "CASH_MOVEMENT_ADDED"
} as const

export type WSEvent = typeof WSEvent[keyof typeof WSEvent]