"""add restaurant_id to order_item

Revision ID: 366b536e4628
Revises: 5ca3137cd70a
Create Date: 2026-02-22 18:57:10.395805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '366b536e4628'
down_revision: Union[str, Sequence[str], None] = '5ca3137cd70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('restaurant_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_order_items_restaurant_id'), 'order_items', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'restaurants', ['restaurant_id'], ['id'])
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('restaurants', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('restaurants', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('restaurants', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'plan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('restaurants', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('restaurants', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_restaurant_id'), table_name='order_items')
    op.drop_column('order_items', 'restaurant_id')
    # ### end Alembic commands ###
