"""auditoria

Revision ID: 789ad8c3f1b5
Revises: a5fb39b05ac8
Create Date: 2026-08-12 03:21:56.691752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '789ad8c3f1b5'
down_revision: Union[str, Sequence[str], None] = 'a5fb39b05ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Las órdenes siempre deben tener fecha de creación.
    op.alter_column(
        "orders",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()")
    )

    # El layout siempre debe tener configuración de grilla y snap.
    op.alter_column(
        "restaurant_layout",
        "grid_size",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("40")
    )

    op.alter_column(
        "restaurant_layout",
        "snap_to_grid",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("true")
    )

    # restaurant_id ya es PRIMARY KEY, por lo que este UNIQUE es redundante.
    op.drop_constraint(
        "restaurant_layout_restaurant_id_key",
        "restaurant_layout",
        type_="unique"
    )

    # Toda configuración persistida debe tener puerto SMTP definido.
    op.alter_column(
        "system_settings",
        "smtp_port",
        existing_type=sa.INTEGER(),
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'smtp_port',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('restaurant_layout_restaurant_id_key'), 'restaurant_layout', ['restaurant_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('restaurant_layout', 'snap_to_grid',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('restaurant_layout', 'grid_size',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('40'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
