"""restaurant layout

Revision ID: a4b707b32039
Revises: e2398672eb07
Create Date: 2026-03-30 02:10:53.189414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b707b32039'
down_revision: Union[str, Sequence[str], None] = 'e2398672eb07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_domain_events_restaurant'), table_name='domain_events')
    op.create_index(op.f('ix_domain_events_id'), 'domain_events', ['id'], unique=False)
    op.create_index(op.f('ix_domain_events_restaurant_id'), 'domain_events', ['restaurant_id'], unique=False)
    op.create_foreign_key(
    "fk_domain_events_restaurant",
    "domain_events",
    "restaurants",
    ["restaurant_id"],
    ["id"]
)
    op.create_table(
        "restaurant_layout",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("restaurant_id", sa.Integer(), sa.ForeignKey("restaurants.id"), nullable=False, unique=True),
        sa.Column("width", sa.Integer(), nullable=False, server_default="900"),
        sa.Column("height", sa.Integer(), nullable=False, server_default="500"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_domain_events_restaurant", "domain_events", type_="foreignkey")
    op.drop_index(op.f('ix_domain_events_restaurant_id'), table_name='domain_events')
    op.drop_index(op.f('ix_domain_events_id'), table_name='domain_events')
    op.create_index(op.f('idx_domain_events_restaurant'), 'domain_events', ['restaurant_id'], unique=False)
    op.drop_table("restaurant_layout")
