"""add cash_register audit fields

Revision ID: b30663f913d9
Revises: 9607a137eec7
Create Date: 2026-03-01 21:47:58.915981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30663f913d9'
down_revision: Union[str, Sequence[str], None] = '9607a137eec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_registers', sa.Column('is_open', sa.Boolean(), nullable=False))
    op.add_column('cash_registers', sa.Column('opened_by_id', sa.Integer(), nullable=True))
    op.add_column('cash_registers', sa.Column('closed_by_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_cash_registers_id'), table_name='cash_registers')
    op.create_foreign_key(None, 'cash_registers', 'users', ['opened_by_id'], ['id'])
    op.create_foreign_key(None, 'cash_registers', 'users', ['closed_by_id'], ['id'])
    op.create_unique_constraint('uq_category_name_per_restaurant', 'categories', ['restaurant_id', 'name'])
    op.create_index('ix_orders_restaurant_status', 'orders', ['restaurant_id', 'status'], unique=False)
    op.create_unique_constraint('uq_station_name_per_restaurant', 'production_stations', ['restaurant_id', 'name'])
    op.create_unique_constraint('uq_product_name_per_restaurant', 'products', ['restaurant_id', 'name'])
    op.alter_column('tables', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('tables', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_tables_external_id'), table_name='tables')
    op.drop_constraint(op.f('tables_number_key'), 'tables', type_='unique')
    op.create_index('ix_table_restaurant_active', 'tables', ['restaurant_id', 'active'], unique=False)
    op.create_unique_constraint('uq_table_external_per_restaurant', 'tables', ['restaurant_id', 'external_id'])
    op.create_unique_constraint('uq_table_number_per_restaurant', 'tables', ['restaurant_id', 'number'])
    op.drop_constraint(op.f('tables_restaurant_id_fkey'), 'tables', type_='foreignkey')
    op.create_foreign_key(None, 'tables', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='foreignkey')
    op.create_foreign_key(op.f('tables_restaurant_id_fkey'), 'tables', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint('uq_table_number_per_restaurant', 'tables', type_='unique')
    op.drop_constraint('uq_table_external_per_restaurant', 'tables', type_='unique')
    op.drop_index('ix_table_restaurant_active', table_name='tables')
    op.create_unique_constraint(op.f('tables_number_key'), 'tables', ['number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tables_external_id'), 'tables', ['external_id'], unique=True)
    op.alter_column('tables', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tables', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('uq_product_name_per_restaurant', 'products', type_='unique')
    op.drop_constraint('uq_station_name_per_restaurant', 'production_stations', type_='unique')
    op.drop_index('ix_orders_restaurant_status', table_name='orders')
    op.drop_constraint('uq_category_name_per_restaurant', 'categories', type_='unique')
    op.drop_constraint(None, 'cash_registers', type_='foreignkey')
    op.drop_constraint(None, 'cash_registers', type_='foreignkey')
    op.create_index(op.f('ix_cash_registers_id'), 'cash_registers', ['id'], unique=False)
    op.drop_column('cash_registers', 'closed_by_id')
    op.drop_column('cash_registers', 'opened_by_id')
    op.drop_column('cash_registers', 'is_open')
    # ### end Alembic commands ###
