"""initial schema

Revision ID: f186e0156a8f
Revises: 
Create Date: 2026-08-24 16:20:53.715467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f186e0156a8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_restaurants_external_id'), 'restaurants', ['external_id'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_category_name_per_restaurant')
    )
    op.create_table('event_outbox',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_outbox_cleanup', 'event_outbox', ['status', 'processed_at'], unique=False)
    op.create_index('idx_event_outbox_failed_cleanup', 'event_outbox', ['status', 'retries', 'created_at'], unique=False)
    op.create_index('ix_event_outbox_created', 'event_outbox', ['created_at'], unique=False)
    op.create_index('ix_event_outbox_event_type', 'event_outbox', ['event_type'], unique=False)
    op.create_index('ix_event_outbox_restaurant', 'event_outbox', ['restaurant_id'], unique=False)
    op.create_index('ix_event_outbox_status', 'event_outbox', ['status'], unique=False)
    op.create_table('production_stations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_station_name_per_restaurant')
    )
    op.create_table('restaurant_layout',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('grid_size', sa.Integer(), nullable=False),
    sa.Column('snap_to_grid', sa.Boolean(), nullable=False),
    sa.Column('background_image', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('system_settings',
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('smtp_host', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.String(), nullable=True),
    sa.Column('smtp_from', sa.String(), nullable=True),
    sa.Column('smtp_use_tls', sa.Boolean(), nullable=False),
    sa.Column('backup_email', sa.String(), nullable=True),
    sa.Column('backup_frequency', sa.Enum('manual', 'daily', 'weekly', 'monthly', name='backupfrequency', native_enum=False, length=20), nullable=False),
    sa.Column('backup_retention_daily', sa.Integer(), nullable=False),
    sa.Column('backup_retention_weekly', sa.Integer(), nullable=False),
    sa.Column('backup_retention_monthly', sa.Integer(), nullable=False),
    sa.Column('backup_time', sa.Time(), nullable=False),
    sa.Column('backup_weekday', sa.Integer(), nullable=True),
    sa.Column('backup_monthday', sa.Integer(), nullable=True),
    sa.Column('backup_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_automatic_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_automatic_backup_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_backup_result', sa.String(), nullable=True),
    sa.Column('backup_keep_local', sa.Boolean(), nullable=False),
    sa.Column('backup_send_email', sa.Boolean(), nullable=False),
    sa.Column('backup_timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_table('tables',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('shape', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'external_id', name='uq_table_external_per_restaurant'),
    sa.UniqueConstraint('restaurant_id', 'number', name='uq_table_number_per_restaurant')
    )
    op.create_index('ix_table_restaurant_active', 'tables', ['restaurant_id', 'active'], unique=False)
    op.create_index(op.f('ix_tables_restaurant_id'), 'tables', ['restaurant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'WAITER', 'KITCHEN', 'CASHIER', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'username', name='uq_user_username_per_restaurant')
    )
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.create_table('cash_registers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_by_id', sa.Integer(), nullable=False),
    sa.Column('closed_by_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expected_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('counted_cash', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_sales', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payments_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opened_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_registers_restaurant_id'), 'cash_registers', ['restaurant_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'SENT', 'IN_PROGRESS', 'READY', 'CLOSED', 'CANCELLED', name='orderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_external_id'), 'orders', ['external_id'], unique=True)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index('ix_orders_restaurant_status', 'orders', ['restaurant_id', 'status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['production_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('restaurant_id', 'name', name='uq_product_name_per_restaurant')
    )
    op.create_index(op.f('ix_products_restaurant_id'), 'products', ['restaurant_id'], unique=False)
    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('cash_in', 'cash_out', name='cashmovementtype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cash_movements_register', 'cash_movements', ['cash_register_id'], unique=False)
    op.create_index('ix_cash_movements_register_type', 'cash_movements', ['cash_register_id', 'type'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'IN_PROGRESS', 'READY', 'DELIVERED', 'CANCELLED', name='orderitemstatus'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order_status', 'order_items', ['order_id', 'status'], unique=False)
    op.create_index(op.f('ix_order_items_restaurant_id'), 'order_items', ['restaurant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cash_register_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cash_register_id'], ['cash_registers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_restaurant_id'), 'payments', ['restaurant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_restaurant_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_restaurant_id'), table_name='order_items')
    op.drop_index('ix_order_items_order_status', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_cash_movements_register_type', table_name='cash_movements')
    op.drop_index('ix_cash_movements_register', table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_products_restaurant_id'), table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_restaurant_status', table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_external_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_cash_registers_restaurant_id'), table_name='cash_registers')
    op.drop_table('cash_registers')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tables_restaurant_id'), table_name='tables')
    op.drop_index('ix_table_restaurant_active', table_name='tables')
    op.drop_table('tables')
    op.drop_table('system_settings')
    op.drop_table('restaurant_layout')
    op.drop_table('production_stations')
    op.drop_index('ix_event_outbox_status', table_name='event_outbox')
    op.drop_index('ix_event_outbox_restaurant', table_name='event_outbox')
    op.drop_index('ix_event_outbox_event_type', table_name='event_outbox')
    op.drop_index('ix_event_outbox_created', table_name='event_outbox')
    op.drop_index('idx_event_outbox_failed_cleanup', table_name='event_outbox')
    op.drop_index('idx_event_outbox_cleanup', table_name='event_outbox')
    op.drop_table('event_outbox')
    op.drop_table('categories')
    op.drop_index(op.f('ix_restaurants_external_id'), table_name='restaurants')
    op.drop_table('restaurants')

    # --------------------------------------------------
    # Eliminar ENUM nativos de PostgreSQL.
    #
    # Al eliminar las tablas PostgreSQL no elimina
    # automáticamente los tipos ENUM asociados.
    # --------------------------------------------------
    op.execute(
        "DROP TYPE IF EXISTS paymentmethod"
    )

    op.execute(
        "DROP TYPE IF EXISTS orderitemstatus"
    )

    op.execute(
        "DROP TYPE IF EXISTS orderstatus"
    )

    op.execute(
        "DROP TYPE IF EXISTS userrole"
    )
    # ### end Alembic commands ###
