"""align remaining backend model

Revision ID: f2b920bbec2b
Revises: 789ad8c3f1b5
Create Date: 2026-08-12 04:07:15.221597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2b920bbec2b'
down_revision: Union[str, Sequence[str], None] = '789ad8c3f1b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cash_registers', 'opened_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cash_registers', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.alter_column('tables', 'shape',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_tables_id'), table_name='tables')
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.create_unique_constraint('uq_user_username_per_restaurant', 'users', ['restaurant_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_username_per_restaurant', 'users', type_='unique')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.alter_column('users', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_tables_id'), 'tables', ['id'], unique=False)
    op.alter_column('tables', 'shape',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.alter_column('cash_registers', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cash_registers', 'opened_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
