"""add table coordinates

Revision ID: fa7705341950
Revises: b30663f913d9
Create Date: 2026-03-15 02:39:50.294892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7705341950'
down_revision: Union[str, Sequence[str], None] = 'b30663f913d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "tables",
        sa.Column("x", sa.Integer(), nullable=False, server_default="0")
    )

    op.add_column(
        "tables",
        sa.Column("y", sa.Integer(), nullable=False, server_default="0")
    )

    op.add_column(
        "tables",
        sa.Column("capacity", sa.Integer(), nullable=False, server_default="4")
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tables', 'shape')
    op.drop_column('tables', 'capacity')
    op.drop_column('tables', 'y')
    op.drop_column('tables', 'x')
    # ### end Alembic commands ###
